cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add, name="add"),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('delete/<int:product_id>/',views.delete_cart, name="delete_cart"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce_app.urls')),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_app/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce_app'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('shop/<slug:c_slug>/', views.allProdCat, name = 'products_by_category'),
    path('shop/<slug:c_slug>/<slug:product_slug>/', views.productDetails, name = 'prodCatDetail'),

]

searchapp/urls.py
from django.urls import path
from . import views 
app_name ='searchapp'

urlpatterns =[
    path('', views.SearchResult, name="searchResult")
]

cart/models.py
from django.db import models
from ecommerce_app . models import Products
# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=50, blank=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']
    
    def __str__(self):
        return self.cart_id
    
class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'CartItem'

    def total(self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return '{}'.format(self.product)
    

ecommerce_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    disc = models.TextField(max_length=1000, blank=True)
    image = models.ImageField(upload_to='catogery', blank=True)
    

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

        # for getting url

    def get_url(self):
        return reverse('ecommerce_app:products_by_category',  args=[(self.slug)])

        # setting proper name

    def __self__(self):
        return '{}'.format(self.name)


class Products(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    catogery = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default= False)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now= True)
    
    def get_url(self):
        return reverse('ecommerce_app:prodCatDetail', args=[self.catogery.slug, self.slug])
    

    class Meta:
        # db_table = 'Products'
        ordering =  ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'



    def __str__(self):
        return '{}'.format(self.name)

searchapp/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import get_object_or_404, render, redirect
from ecommerce_app . models import Products
from . models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key

    if not cart:
        cart = request.session.create()
    return cart
def add(request, product_id):
    product = Products.objects.get(id = product_id)
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product= product, cart = cart)
        # check whether item is out of stock or not
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product = product, quantity = 1, cart = cart)

    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_item=None):

    try:
        cart = Cart.objects.get(cart_id =_cart_id(request))
        cart_item = CartItem.objects.filter(cart=cart, active=True)
        for _item in cart_item:
            total += (_item.product.price * _item.quantity)
            counter += _item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_item=cart_item, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product = product, cart = cart)
    try:

        if cart_item.quantity >= 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    
    return redirect('cart:cart_detail')


def delete_cart(request, product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Products, id= product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    
    return redirect('cart:cart_detail')

ecommerce_app/views.py
from django.shortcuts import get_object_or_404, render
from .models import Products, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage

def index(request):
    return render(request, 'index.html')
#  First page , getting slug and dtails
def allProdCat(request, c_slug=None):
    c_page = None
    product_list = None

    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Products.objects.filter(catogery=c_page, available=True)
    else:
        product_list = Products.objects.filter(available=True)
    
    paginator = Paginator(product_list, 3)

    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'catogery': c_page, 'products': products})

#  For product details

def productDetails(request, c_slug, product_slug):
    try:
        product = Products.objects.get(catogery__slug = c_slug, slug = product_slug)
    except Exception as e:
        raise e
    
    return render(request, 'product.html',{'product':product})

searchapp/views.py
from django.shortcuts import render

# Create your views here.
from ecommerce_app.models import Products
from django.db.models import Q

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Products.objects.all().filter(Q( name__contains = query) | Q(desc__contains = query))
    return render(request, 'search.html', {'query':query, 'products':products})

templates/cart.html
{% extends 'index.html' %}
{% load static %}

{% block metadescription %}
  This is cart page. proceed to review your items and place the order
{% endblock %}
{% block title %}
cart
{% endblock %}
{% block content %}
{% if not cart_item %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my title"> Your Shoping Cart is Empty</h1><br>
        <p class="text-center">
            Please Click <a href="{% url 'ecommerce_app:allProdCat' %}">Here</a>to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shoping cart</h1>
        <br>


    </div>
    <div class="row mx-auto"> 
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">

                    <tr>
                        <th colspan="5">
                            Your Items

                        </th>
                    </tr>

                </thead>

                <tbody>
                    {% for item in cart_item %}
                    <tr>
                        <td>
                            <a href="item.product.get_absolute_url"><img src="{{item.product.image.url}}" style="height: 200px; width: 200px;" class="float-left rounded custom_image"></a>
                        </td>
                        <td class="text-left">
                            {{item.product.name}}
                            <br>
                            SKU: {{item_product.id}}
                            <br>
                            Price:$ {{item.product.price}}
                            <br>
                            Qty:  {{item.quantity}} * ${{item }}
                        </td>
                        <td>
                            $ {{item.total}}
                        </td>
                        {% if item.quantity < item.product.stock %}
                        <td>
                          
                             <a href="{% url 'cart:add' item.product.id %}" class="custom-a" ><i class="fa-solid fa-plus"></i></a>
                              &nbsp;
                            
                              <a href="{% url 'cart:cart_remove' item.product.id %}" class="custom_a"><i class="fa-solid fa-minus"></i></a>
                              &nbsp;
                              <a href="{% url 'cart:delete_cart' item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>
                              &nbsp;

                            

                        </td>
                        {% else %}
                        <td>
                           
                           
                            <a href="{% url 'cart:delete_cart' item.product.id %}" class="custom_a"><i class="fa-solid fa-trash"></i></a>
                            &nbsp;
                            <a href="{% url 'cart:cart_remove' item.product.id %}" class="custom_a"><i class="fa-solid fa-minus "></i></a>
                            &nbsp;

                       </td>


                    </tr>
                    {% endif %}
                    
                    
                    {% endfor %}
                </tbody>
                


            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">

                <thead class="my_custom_thead">
                    <tr>
                        <th>CheckOut</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Please review your shopping cart items before proceeding with the order payment.</td>
                    </tr>
                    <tr>
                        <td class="text-left">Your Total Bill: <strong>{{total}}</strong></td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto">
                <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>

        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/category.html
{% extends 'index.html' %}
{% load static %}

{% block metadescription %}
    {% if catogery %}
        {{ catogery.description | truncatewords:155 }}
    {% else %}
        Welcome to ABC Store
    {% endif %}
{% endblock %}

{% block title %}
    {% if catogery %}
        {{ catogery.name }} - ABC Store
    {% else %}
        New collection
    {% endif %}
{% endblock %}

{% block content %}
    {% if catogery %}
        <div>
            <div class="row my_row_class">
                <div class="mx_auto">
                    <p><a href="{% url 'ecommerce_app:allProdCat' %}">Our Product Collection</a></p>
                </div>    
            </div>
        </div>

        <div class="mx_auto">
            <!-- <img class="my_image"  src="{{ catogery.image.url }}" style="height: 300px; width: 300px;" alt="{{ catogery.name }}" > -->
        </div>
        <br>
        <div>
            <h1 class="text-center my_title">{{ catogery.name }}</h1>
            <p class="text-jesttify">{{ catogery.disc }}</p>
        </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="boom">
        </div>

        <br>
        <div>
            <h1 class="text-center my_title">Our Products Collections</h1>
            <p class="text-jesttify">
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
                the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of
                type and scrambled it to make a type specimen book. It has survived not only five centuries, but
                also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in
                the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
    {% endif %}

    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
                    <div class="card text-center" style="min-width: 20rem;min-height: 20rem;">
                        <a href="{{product.get_url}}">
                            <img class="card-img-top my_image" src="{{ product.image.url }}" style="height: 300px; width: 300px;" alt="{{ product.name }}">
                        </a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>${{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}
            
            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class="btn btn-sm btn-light" {% if products.number == pg %} active {% endif %}>{{pg}}</a>
                    {% endfor %}

            </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copyright:ABC tech pvt ltd. All rights are Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
      <a href="{% url 'ecommerce_app:allProdCat' %}">  <img src="{% static 'img/logo.png' %}" height="200px" weight="200px" alt="logoimage" > </a>
    </center>
</header>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css '%}" rel="stylesheet" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/16b1d188ad.js" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}/title>
</head>
<body>
    <div class="container">
    
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}

    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          
          <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              shop
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#"><i class="fa-solid fa-cart-shopping"></i>Your cart()</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" ><i class="fa-solid fa-cart-shopping"></i>Your cart()</a>
          </li>
        </ul>
        <form class="d-flex" method="get" action="{% url 'searchapp:searchResult' %}">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name ="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i>
          </button>
        </form>
      </div>
    </div>
  </nav>

templates/product.html
{% extends 'index.html' %}
{% load static %}
{% block metadescription %}
 
        {{product.desc | truncatewords:155}}
 
        welcome to ABC store where you can buys different items ...

{% endblock %}




{% block title %}
    {% if catogery %}
        {{product.name}}
   
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'ecommerce_app:allProdCat' %}">Home</a> | 
            <a href="{{product.catogery.get_url}}" >{{product.name}}</a>|
            {{product.name}}</p>
    </div>

</div >
<div class="container">

<br>

<div class="row"> 
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
         <div style="min-width: 18rem;">
            <img src="{{product.image.url}}" style="width: 300px; height:300px"  alt="{{product.name}}">

        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>

            
            <h1 class="my_product_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">product discription</p>
            <p class="text-jestify my_pro_text">{{product.desc}}</p>

            {% if product.stock <= 0 %}
                <p><b>Out of stock</b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add' product.id %}">Add to cart</a>
            {% endif %}
        </div> </div></div></div>

{% endblock %}

templates/search.html
{% extends 'index.html' %}
{% load static %}

{% block metadescription %}
  We have verity of products
{% endblock %}
{% block title %}
search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for <b>"{{query}}"</b></p>

</div>

    <div class="container">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
                    <div class="card text-center" style="min-width: 20rem;min-height: 20rem;">
                        <a href="{{product.get_url}}">
                            <img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>${{ product.price }}</p>
                        </div>
                    </div>
                </div>
         
            {% empty %}
            <div class="row mx_auto ">
                <p class="text-center">
                    0 result found
                </p>

            </div>
            {% endfor %}
        </div>
</div>
{% endblock %}